USE [master]
GO

/****** Object:  Database [CONTEC]    Script Date: 17/05/2019 12:16:49 ******/
CREATE DATABASE [CONTEC]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CONTEC', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\CONTEC.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CONTEC_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\CONTEC_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [CONTEC] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CONTEC].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CONTEC] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CONTEC] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CONTEC] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CONTEC] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CONTEC] SET ARITHABORT OFF 
GO

ALTER DATABASE [CONTEC] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CONTEC] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CONTEC] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CONTEC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CONTEC] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CONTEC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CONTEC] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CONTEC] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CONTEC] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CONTEC] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CONTEC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CONTEC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CONTEC] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CONTEC] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CONTEC] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CONTEC] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CONTEC] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CONTEC] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CONTEC] SET  MULTI_USER 
GO

ALTER DATABASE [CONTEC] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CONTEC] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CONTEC] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CONTEC] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CONTEC] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CONTEC] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CONTEC] SET  READ_WRITE 
GO


