USE [CONTEC]
GO

/****** Object:  StoredProcedure [dbo].[P_CONSULTA_DADOS_CLIENTE]    Script Date: 17/05/2019 12:16:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[P_CONSULTA_DADOS_CLIENTE]( -- [P_CONSULTA_DADOS_CLIENTE] '', '46282096000056'
	@ID INT,
	@CNPJ VARCHAR(50)
) AS
BEGIN
	
	--DECLARE @ID_CLIENTE INT = (SELECT ID FROM CLIENTES WHERE @CNPJ = CNPJ)

	--TRAZ AS INFORMAÇÕES DO CLIENTE
	SELECT
		*
	FROM CLIENTES C
	INNER JOIN CONTATOS_CLIENTES CC ON CC.ID_CLI = C.ID
	INNER JOIN ENDERECO_CLIENTES E ON E.ID_CLI = C.ID
	/*WHERE C.CNPJ LIKE @CNPJ + '%'
	AND (@ID_CLIENTE = CASE WHEN @ID_CLIENTE IS NOT NULL THEN CC.ID_CLI END
				OR
		C.ID = C.ID
		)*/
	WHERE C.ID = CASE WHEN ISNULL(@ID,'') <> '' AND ISNULL(@CNPJ,'') = '' THEN @ID END
					OR
		  C.CNPJ = CASE WHEN ISNULL(@CNPJ,'') <> '' AND ISNULL(@ID,'') = '' THEN @CNPJ END
					OR
		 C.ID = CASE WHEN ISNULL(@ID,'') = '' AND ISNULL(@CNPJ,'') = '' THEN C.ID END
END
GO

