USE [CONTEC]
GO

/****** Object:  StoredProcedure [dbo].[P_DELETA_CLIENTE]    Script Date: 17/05/2019 12:16:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[P_DELETA_CLIENTE]( --[P_DELETA_CLIENTE] 1
	@Id INT
) AS
BEGIN
	BEGIN TRY
		--SEGURA TRANSAÇÃO
		BEGIN TRAN
			--DELETA UM CLIENTE ESPECÍFICO
			DELETE FROM CONTATOS_CLIENTES WHERE ID_CLI = @Id
			DELETE FROM ENDERECO_CLIENTES WHERE ID_CLI = @Id
			DELETE FROM CLIENTES WHERE ID = @Id
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		--VOLTA TRANSAÇÃO
		ROLLBACK TRAN
	END CATCH
END
GO

