USE [CONTEC]
GO

/****** Object:  Table [dbo].[CONTATOS_CLIENTES]    Script Date: 17/05/2019 12:11:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CONTATOS_CLIENTES](
	[ID] [int] NOT NULL,
	[DDD] [char](2) NOT NULL,
	[TelefoneCorporativo] [varchar](10) NOT NULL,
	[TelefoneCelCorporativo] [varchar](10) NULL,
	[Email] [varchar](50) NULL,
	[ID_CLI] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CONTATOS_CLIENTES]  WITH CHECK ADD  CONSTRAINT [FK_CONTATOS_CLIENTES] FOREIGN KEY([ID_CLI])
REFERENCES [dbo].[CLIENTES] ([ID])
GO

ALTER TABLE [dbo].[CONTATOS_CLIENTES] CHECK CONSTRAINT [FK_CONTATOS_CLIENTES]
GO

