USE [CONTEC]
GO

/****** Object:  Table [dbo].[CLIENTES]    Script Date: 17/05/2019 12:09:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CLIENTES](
	[ID] [int] NOT NULL,
	[RazaoSocial] [varchar](100) NOT NULL,
	[NomeFantasia] [varchar](50) NOT NULL,
	[CNPJ] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


